apiVersion: v1
kind: Service
metadata:
  name: ctfd-svc
  namespace: ctfd
spec:
  selector:
    app: ctfd
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30008
  type: NodePort
