apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ctfd-to-db
  namespace: ctfd
spec:
  podSelector:
    matchLabels:
      app: mysql
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: ctfd
      ports:
        - protocol: TCP
          port: 3306
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-ingress-to-ctfd
  namespace: ctfd
spec:
  podSelector:
    matchLabels:
      app: ctfd
  policyTypes:
    - Ingress
  ingress:
    - ports:
        - protocol: TCP
          port: 8000
